In [1]:
    import annodize, typing
    annodize

<module 'annodize' from '/Users/tonyfast/annodize/annodize.py'>

In [2]:
    import pandas
    np = pandas.np
    xx: annodize.Priority(tuple('pandas.Series numpy.array np.array list'.split()), _coerce=True) = [10]
    annodize.annodize(__name__)
    q = xx
    annodize.annodize(__name__)
    assert q is xx
    xx

0    10
dtype: int64

In [3]:
    del pandas
    annodize.annodize(__name__)
    xx

array([10])

In [4]:
    del np
    annodize.annodize(__name__)
    xx

[10]

In [5]:
    import numpy
    annodize.annodize(__name__)
    xx

array([10])

In [6]:
    import pandas;
    annodize.annodize(__name__) or xx

0    10
dtype: int64

In [7]:
    del pandas, numpy
    annodize.annodize(__name__)
    xx

[10]

In [8]:
    %load_ext annodize

In [9]:
    xx

[10]

In [10]:
    import pandas, numpy

In [11]:
    q = xx
    xx

0    10
dtype: int64

In [12]:
    assert q is xx

In [13]:
    del pandas

In [14]:
    xx

array([10])

In [15]:
    del numpy

In [16]:
    xx

[10]

In [17]:
    %unload_ext annodize

In [18]:
    import pandas

In [19]:
    xx

[10]

In [20]:
    annodize.annodize(__name__)
    xx

0    10
dtype: int64

In [21]:
    %load_ext annodize

In [22]:
    import panel

In [23]:
    foo: annodize.Forward('panel.widgets.IntSlider', _observe='value', _coerce=True)  =2  

IntSlider(value=2)

In [24]:
    foo: annodize.Forward('ipywidgets.IntSlider', _observe='value', _coerce=True)

In [25]:
    import ipywidgets

IntSlider(value=2, description='foo')

In [26]:
    import ipywidgets

In [27]:
    del ipywidgets

In [28]:
    foo: annodize.Forward('ipywidgets.IntSlider', _observe='value', _coerce=True)    

In [29]:
    import ipywidgets
    foo: annodize.Forward('ipywidgets.IntSlider', _observe='value', _coerce=True)    

IntSlider(value=2, description='foo')

In [30]:
    foo

2

In [31]:
    assert foo is __annotations__['foo'].__forward_display__.value
    __annotations__['foo'].__forward_display__.value = 10

In [32]:
    assert foo is 10

In [33]:
    %unload_ext annodize

In [34]:
    with __import__('importnb').Notebook():
        import test_types

In [35]:
    import ipywidgets
    bar: int = 9
    baz: str = 'help me'
    annodize.annodize(__name__, test_types.__annotations__)

IntText(value=9, description='bar')

Text(value='help me', description='baz')

In [36]:
    jawn: typing.List[int] = range(3)
    annodize.annodize(__name__, test_types.__annotations__)
    jawn

0    0
1    1
2    2
dtype: int64

In [37]:
    jawn: typing.List[float] = range(3)
    annodize.annodize(__name__, test_types.__annotations__)
    jawn

0    0.0
1    1.0
2    2.0
dtype: float64

In [38]:
    del pandas
    jawn: typing.List[float] = range(3)
    annodize.annodize(__name__, test_types.__annotations__)
    jawn

range(0, 3)

In [39]:
    with __import__('importnb').Notebook(): import test_types
    test_types.__annotations__

{'int': Forward('ipywidgets.IntText'),
 'float': Forward('ipywidgets.FloatText'),
 'str': Forward('ipywidgets.Text'),
 'list': Priority(('pandas.Series', 'numpy.array', 'np.array', 'list')),
 typing.List[int]: Forward('pandas.Series'),
 typing.List[float]: Forward('pandas.Series'),
 typing.List[list]: Priority((Forward('pandas.DataFrame'), Forward('numpy.array'), Forward('np.array')))}

In [40]:
    jawn: typing.List[list] = [list(range(3))]*3
    annodize.annodize(__name__, test_types.__annotations__)
    jawn

[[0, 1, 2], [0, 1, 2], [0, 1, 2]]

In [41]:
    import pandas
    annodize.annodize(__name__, test_types.__annotations__)
    jawn

0    1    2
0  0.0  1.0  2.0
1  0.0  1.0  2.0
2  0.0  1.0  2.0